services:
  - type: web
    name: jwash-backend
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    root: backend
    envVars:
      - key: JWT_SECRET
        value: "REPLACE_WITH_SECRET"
      - key: NODE_ENV
        value: "production"